apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claudeopus47
resources:
  - namespace.yaml
  - registry-pull-secret.yaml
  - deployment.yaml
  - service.yaml
  - live-ingress.yaml
  - live-www-redirect-ingress.yaml
  - preview-ingress.yaml
