---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claudeopus47-registry
  namespace: claudeopus47
spec:
  encryptedData:
    .dockerconfigjson: AgAMZMuxuuK5dudA2ei6H733t50eTTlgfVmpygO16nBkhLh5wZoc6aTGrh/QtQY7+UdSQkQ4Pc2XnMr+mH4kf5t2+gNB0ZPRTXQZ9sVls1orU6DQtoDczey599u/LeJ0PSUcbpeqAnNNJN1a1T4SXlZlfTeSHX2jQVpHCqGjZ9SbYedZXNL4GSWao23cmoCYwe5F0fWjzk2yDP9ofjeYJ5lfspKtmAqEskUKBWI75OqKTwasTPLmbuZdTqKUb7BghjkQLDCRBNtlN0FgdESags8rlp0lYT2zZDLSnllwkNOsLjV6lHdHU15ubTAoui1knwDZUzu0ruRaTcXnpNsrTB4nAjCAG6ZvafkntcgIUcO8a/RE2IjcMaoYUnUiLtMssOYJUFr+41aHTggLgEdmTKmtkYRZMEqbXe3b2Gfj9G7++XPuiE3FISLOiM6ZYLxEYqF8ZO8HMd5lffM9ADxfyz8ISzqLpQcz1+Q3tr2AqteN90EKUlPp7n3WHNlRWl7q319ScGCN2zADQcpxuxPUOijna6kwlXRsnZsA6mDwyntHxYc3rfCTA1B9aKB5jBHYv34ESUDL9G7JRE2hSAS2pMrmtIDT9hXNqMq/qkqidzpOqIJ4idq2QRPsmrl0WM8X7h4V3Qp+uC6fHQFqn+0cM3+duFmFQhwvyvsFZ1k1Yg1xPd/w/jDe6E6KUDBqXhZz4FNyKNpYjgM3pwfY26/rv0y0JNw39I0qkaQjeEgNTR6gvbWSEdEWYzHGHZkELX7bhrUnOQ5gr9G0yXVcnKomOrDlBwU7zjWeJJALYNNwkHkAf/0VaGMCclozivE0hiFjkFoGPG7cYyHd2rguyUa8YLqVIKgDWrR72BlkN7BpEHryyAYahxJfY5zkESr1jM/h1ABvJNCbg5A/x0nXZlaXxgx9uhNzR3bq/7M3uEXsGoe6t18G7wjJpapAcFp70727xwKXuUy7fiMJbq2AJdfdPES9Gkq1UV21SHlChtndNNen9SzsJpWYN7gz1uXA1eYExhwcbPzoGDgstnSk51sfKaKV4fZSiRYquinxVo4A6XYt+Rsb+BX5vNexTw+mjQK5pD61UMdl/yJA/4oUGVzeVTYrQawPfo+VTU6K992AnvXnT/B79FuM4Auo4BbEs4os6Y0GMBumE4CFzPHiJJRRFpXWit2YrOw9VKhNTB1NUgcxXML1o3F/wJdnAGGw5sEqt2ZU4aV80p4xXaCuGw==
  template:
    metadata:
      name: claudeopus47-registry
      namespace: claudeopus47
    type: kubernetes.io/dockerconfigjson
